package com.doerit.util;

public enum SignInType {
	EMPLOYEE, HEAD_OFFICE, DISTRIBUTION_CENTER, DISTRIBUTION_CENTER_RETAILER,
	RETAILER, CORPORATE, DIRECT_PROJECT, DISTRIBUTION_CENTER_PROJECT, OUTLET_CENTER;
}
