DROP TABLE IF EXISTS tbl_activity_logger;

CREATE TABLE tbl_activity_logger(
	ID CHAR(32) NOT NULL PRIMARY KEY,
	RELATE_KEY CHAR(32) NOT NULL,
	MESSAGE_TYPE CHAR(32) NOT NULL,
	MESSAGE CHAR(255),
	DESCRIPTION TEXT,
	ACCESS_HOST CHAR(64),
	INSERT_USER_ID CHAR(32) DEFAULT NULL,
	UPDATE_USER_ID  CHAR(32) DEFAULT NULL,
	INSERT_DATETIME DATETIME DEFAULT NULL,
	UPDATE_DATETIME DATETIME DEFAULT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='sign in, job related, edit delete';