package com.doerit.model;

import java.util.Date;

public class Action {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_action.ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_action.ACTION_NAME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String actionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_action.NAME_SPACE
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String nameSpace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_action.CONFIGURATION_FILE_NAME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String configurationFileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_action.COMMENT
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_action.STATUS
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_action.SORT_ORDER
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private Integer sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_action.INSERT_USER_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String insertUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_action.INSERT_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private Date insertDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_action.UPDATE_USER_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_action.UPDATE_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private Date updateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_action.ID
     *
     * @return the value of tbl_action.ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_action.ID
     *
     * @param id the value for tbl_action.ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_action.ACTION_NAME
     *
     * @return the value of tbl_action.ACTION_NAME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getActionName() {
        return actionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_action.ACTION_NAME
     *
     * @param actionName the value for tbl_action.ACTION_NAME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setActionName(String actionName) {
        this.actionName = actionName == null ? null : actionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_action.NAME_SPACE
     *
     * @return the value of tbl_action.NAME_SPACE
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getNameSpace() {
        return nameSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_action.NAME_SPACE
     *
     * @param nameSpace the value for tbl_action.NAME_SPACE
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setNameSpace(String nameSpace) {
        this.nameSpace = nameSpace == null ? null : nameSpace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_action.CONFIGURATION_FILE_NAME
     *
     * @return the value of tbl_action.CONFIGURATION_FILE_NAME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getConfigurationFileName() {
        return configurationFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_action.CONFIGURATION_FILE_NAME
     *
     * @param configurationFileName the value for tbl_action.CONFIGURATION_FILE_NAME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setConfigurationFileName(String configurationFileName) {
        this.configurationFileName = configurationFileName == null ? null : configurationFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_action.COMMENT
     *
     * @return the value of tbl_action.COMMENT
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_action.COMMENT
     *
     * @param comment the value for tbl_action.COMMENT
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_action.STATUS
     *
     * @return the value of tbl_action.STATUS
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_action.STATUS
     *
     * @param status the value for tbl_action.STATUS
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_action.SORT_ORDER
     *
     * @return the value of tbl_action.SORT_ORDER
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_action.SORT_ORDER
     *
     * @param sortOrder the value for tbl_action.SORT_ORDER
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_action.INSERT_USER_ID
     *
     * @return the value of tbl_action.INSERT_USER_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getInsertUserId() {
        return insertUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_action.INSERT_USER_ID
     *
     * @param insertUserId the value for tbl_action.INSERT_USER_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setInsertUserId(String insertUserId) {
        this.insertUserId = insertUserId == null ? null : insertUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_action.INSERT_DATETIME
     *
     * @return the value of tbl_action.INSERT_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public Date getInsertDatetime() {
        return insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_action.INSERT_DATETIME
     *
     * @param insertDatetime the value for tbl_action.INSERT_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_action.UPDATE_USER_ID
     *
     * @return the value of tbl_action.UPDATE_USER_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_action.UPDATE_USER_ID
     *
     * @param updateUserId the value for tbl_action.UPDATE_USER_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_action.UPDATE_DATETIME
     *
     * @return the value of tbl_action.UPDATE_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_action.UPDATE_DATETIME
     *
     * @param updateDatetime the value for tbl_action.UPDATE_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
}