package com.doerit.model;

public class PatientGuardianWithBLOBs extends PatientGuardian {
    
    private String address;
    private String comment;

    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_guardian.ADDRESS
     *
     * @param address the value for tbl_patient_guardian.ADDRESS
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_guardian.COMMENT
     *
     * @return the value of tbl_patient_guardian.COMMENT
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_guardian.COMMENT
     *
     * @param comment the value for tbl_patient_guardian.COMMENT
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}