package com.doerit.model;

import java.util.Date;

public class PatientAdditionalProperty implements InsertUpdate {
    
    private String id;
    private String patientId;
    private String nameKey;
    private String name;
    private String propertyValue;
    private String comment;
    private Byte status;
    private Integer sortOrder;
    private String insertUserId;
    private String updateUserId;
    private Date insertDatetime;
    private Date updateDatetime;

    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_property.ID
     *
     * @param id the value for tbl_patient_property.ID
     *
     * @mbggenerated Sat Jul 15 18:04:19 IST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_property.PATIENT_ID
     *
     * @return the value of tbl_patient_property.PATIENT_ID
     *
     * @mbggenerated Sat Jul 15 18:04:19 IST 2017
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_property.PATIENT_ID
     *
     * @param patientId the value for tbl_patient_property.PATIENT_ID
     *
     * @mbggenerated Sat Jul 15 18:04:19 IST 2017
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId == null ? null : patientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_property.NAME_KEY
     *
     * @return the value of tbl_patient_property.NAME_KEY
     *
     * @mbggenerated Sat Jul 15 18:04:19 IST 2017
     */
    public String getNameKey() {
        return nameKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_property.NAME_KEY
     *
     * @param nameKey the value for tbl_patient_property.NAME_KEY
     *
     * @mbggenerated Sat Jul 15 18:04:19 IST 2017
     */
    public void setNameKey(String nameKey) {
        this.nameKey = nameKey == null ? null : nameKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_property.NAME
     *
     * @return the value of tbl_patient_property.NAME
     *
     * @mbggenerated Sat Jul 15 18:04:19 IST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_property.NAME
     *
     * @param name the value for tbl_patient_property.NAME
     *
     * @mbggenerated Sat Jul 15 18:04:19 IST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_property.PROPERTY_VALUE
     *
     * @return the value of tbl_patient_property.PROPERTY_VALUE
     *
     * @mbggenerated Sat Jul 15 18:04:19 IST 2017
     */
    public String getPropertyValue() {
        return propertyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_property.PROPERTY_VALUE
     *
     * @param propertyValue the value for tbl_patient_property.PROPERTY_VALUE
     *
     * @mbggenerated Sat Jul 15 18:04:19 IST 2017
     */
    public void setPropertyValue(String propertyValue) {
        this.propertyValue = propertyValue == null ? null : propertyValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_property.COMMENT
     *
     * @return the value of tbl_patient_property.COMMENT
     *
     * @mbggenerated Sat Jul 15 18:04:19 IST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_property.COMMENT
     *
     * @param comment the value for tbl_patient_property.COMMENT
     *
     * @mbggenerated Sat Jul 15 18:04:19 IST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_property.STATUS
     *
     * @return the value of tbl_patient_property.STATUS
     *
     * @mbggenerated Sat Jul 15 18:04:19 IST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_property.STATUS
     *
     * @param status the value for tbl_patient_property.STATUS
     *
     * @mbggenerated Sat Jul 15 18:04:19 IST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_property.SORT_ORDER
     *
     * @return the value of tbl_patient_property.SORT_ORDER
     *
     * @mbggenerated Sat Jul 15 18:04:19 IST 2017
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_property.SORT_ORDER
     *
     * @param sortOrder the value for tbl_patient_property.SORT_ORDER
     *
     * @mbggenerated Sat Jul 15 18:04:19 IST 2017
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_property.INSERT_USER_ID
     *
     * @return the value of tbl_patient_property.INSERT_USER_ID
     *
     * @mbggenerated Sat Jul 15 18:04:19 IST 2017
     */
    public String getInsertUserId() {
        return insertUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_property.INSERT_USER_ID
     *
     * @param insertUserId the value for tbl_patient_property.INSERT_USER_ID
     *
     * @mbggenerated Sat Jul 15 18:04:19 IST 2017
     */
    public void setInsertUserId(String insertUserId) {
        this.insertUserId = insertUserId == null ? null : insertUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_property.UPDATE_USER_ID
     *
     * @return the value of tbl_patient_property.UPDATE_USER_ID
     *
     * @mbggenerated Sat Jul 15 18:04:19 IST 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_property.UPDATE_USER_ID
     *
     * @param updateUserId the value for tbl_patient_property.UPDATE_USER_ID
     *
     * @mbggenerated Sat Jul 15 18:04:19 IST 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_property.INSERT_DATETIME
     *
     * @return the value of tbl_patient_property.INSERT_DATETIME
     *
     * @mbggenerated Sat Jul 15 18:04:19 IST 2017
     */
    public Date getInsertDatetime() {
        return insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_property.INSERT_DATETIME
     *
     * @param insertDatetime the value for tbl_patient_property.INSERT_DATETIME
     *
     * @mbggenerated Sat Jul 15 18:04:19 IST 2017
     */
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_patient_property.UPDATE_DATETIME
     *
     * @return the value of tbl_patient_property.UPDATE_DATETIME
     *
     * @mbggenerated Sat Jul 15 18:04:19 IST 2017
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_patient_property.UPDATE_DATETIME
     *
     * @param updateDatetime the value for tbl_patient_property.UPDATE_DATETIME
     *
     * @mbggenerated Sat Jul 15 18:04:19 IST 2017
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
}