package com.doerit.model;

import java.util.Date;

public class UserAccountAction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account_action.ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account_action.USER_ACCOUNT_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String userAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account_action.ACTION_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String actionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account_action.PERMISSION_TYPE
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String permissionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account_action.ASSIGNED_DATE
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private Date assignedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account_action.START_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private Date startDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account_action.END_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private Date endDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account_action.TIMEZONE_ADJUSTMENT_MILLIS
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private Integer timezoneAdjustmentMillis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account_action.COMMENT
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account_action.STATUS
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account_action.SORT_ORDER
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private Integer sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account_action.INSERT_USER_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String insertUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account_action.INSERT_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private Date insertDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account_action.UPDATE_USER_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account_action.UPDATE_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private Date updateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account_action.ID
     *
     * @return the value of tbl_user_account_action.ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account_action.ID
     *
     * @param id the value for tbl_user_account_action.ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account_action.USER_ACCOUNT_ID
     *
     * @return the value of tbl_user_account_action.USER_ACCOUNT_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getUserAccountId() {
        return userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account_action.USER_ACCOUNT_ID
     *
     * @param userAccountId the value for tbl_user_account_action.USER_ACCOUNT_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setUserAccountId(String userAccountId) {
        this.userAccountId = userAccountId == null ? null : userAccountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account_action.ACTION_ID
     *
     * @return the value of tbl_user_account_action.ACTION_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getActionId() {
        return actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account_action.ACTION_ID
     *
     * @param actionId the value for tbl_user_account_action.ACTION_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setActionId(String actionId) {
        this.actionId = actionId == null ? null : actionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account_action.PERMISSION_TYPE
     *
     * @return the value of tbl_user_account_action.PERMISSION_TYPE
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getPermissionType() {
        return permissionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account_action.PERMISSION_TYPE
     *
     * @param permissionType the value for tbl_user_account_action.PERMISSION_TYPE
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setPermissionType(String permissionType) {
        this.permissionType = permissionType == null ? null : permissionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account_action.ASSIGNED_DATE
     *
     * @return the value of tbl_user_account_action.ASSIGNED_DATE
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public Date getAssignedDate() {
        return assignedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account_action.ASSIGNED_DATE
     *
     * @param assignedDate the value for tbl_user_account_action.ASSIGNED_DATE
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setAssignedDate(Date assignedDate) {
        this.assignedDate = assignedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account_action.START_DATETIME
     *
     * @return the value of tbl_user_account_action.START_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public Date getStartDatetime() {
        return startDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account_action.START_DATETIME
     *
     * @param startDatetime the value for tbl_user_account_action.START_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setStartDatetime(Date startDatetime) {
        this.startDatetime = startDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account_action.END_DATETIME
     *
     * @return the value of tbl_user_account_action.END_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public Date getEndDatetime() {
        return endDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account_action.END_DATETIME
     *
     * @param endDatetime the value for tbl_user_account_action.END_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setEndDatetime(Date endDatetime) {
        this.endDatetime = endDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account_action.TIMEZONE_ADJUSTMENT_MILLIS
     *
     * @return the value of tbl_user_account_action.TIMEZONE_ADJUSTMENT_MILLIS
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public Integer getTimezoneAdjustmentMillis() {
        return timezoneAdjustmentMillis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account_action.TIMEZONE_ADJUSTMENT_MILLIS
     *
     * @param timezoneAdjustmentMillis the value for tbl_user_account_action.TIMEZONE_ADJUSTMENT_MILLIS
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setTimezoneAdjustmentMillis(Integer timezoneAdjustmentMillis) {
        this.timezoneAdjustmentMillis = timezoneAdjustmentMillis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account_action.COMMENT
     *
     * @return the value of tbl_user_account_action.COMMENT
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account_action.COMMENT
     *
     * @param comment the value for tbl_user_account_action.COMMENT
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account_action.STATUS
     *
     * @return the value of tbl_user_account_action.STATUS
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account_action.STATUS
     *
     * @param status the value for tbl_user_account_action.STATUS
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account_action.SORT_ORDER
     *
     * @return the value of tbl_user_account_action.SORT_ORDER
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account_action.SORT_ORDER
     *
     * @param sortOrder the value for tbl_user_account_action.SORT_ORDER
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account_action.INSERT_USER_ID
     *
     * @return the value of tbl_user_account_action.INSERT_USER_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getInsertUserId() {
        return insertUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account_action.INSERT_USER_ID
     *
     * @param insertUserId the value for tbl_user_account_action.INSERT_USER_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setInsertUserId(String insertUserId) {
        this.insertUserId = insertUserId == null ? null : insertUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account_action.INSERT_DATETIME
     *
     * @return the value of tbl_user_account_action.INSERT_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public Date getInsertDatetime() {
        return insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account_action.INSERT_DATETIME
     *
     * @param insertDatetime the value for tbl_user_account_action.INSERT_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account_action.UPDATE_USER_ID
     *
     * @return the value of tbl_user_account_action.UPDATE_USER_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account_action.UPDATE_USER_ID
     *
     * @param updateUserId the value for tbl_user_account_action.UPDATE_USER_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account_action.UPDATE_DATETIME
     *
     * @return the value of tbl_user_account_action.UPDATE_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account_action.UPDATE_DATETIME
     *
     * @param updateDatetime the value for tbl_user_account_action.UPDATE_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
}