package com.doerit.model;

import java.util.Date;

public class UserAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account.ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account.USER_NAME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account.USER_PASSWORD
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account.NUMBER_OF_SIGN_IN_ATTEMPTS
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private Byte numberOfSignInAttempts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account.CATEGORY_RELATION_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String categoryRelationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account.RELATION_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String relationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account.ACTIVATE_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private Date activateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account.TERMINATE_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private Date terminateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account.COMMENT
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account.STATUS
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account.SORT_ORDER
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private Integer sortOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account.INSERT_USER_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String insertUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account.INSERT_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private Date insertDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account.UPDATE_USER_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_account.UPDATE_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    private Date updateDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account.ID
     *
     * @return the value of tbl_user_account.ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account.ID
     *
     * @param id the value for tbl_user_account.ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account.USER_NAME
     *
     * @return the value of tbl_user_account.USER_NAME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account.USER_NAME
     *
     * @param userName the value for tbl_user_account.USER_NAME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account.USER_PASSWORD
     *
     * @return the value of tbl_user_account.USER_PASSWORD
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account.USER_PASSWORD
     *
     * @param userPassword the value for tbl_user_account.USER_PASSWORD
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account.NUMBER_OF_SIGN_IN_ATTEMPTS
     *
     * @return the value of tbl_user_account.NUMBER_OF_SIGN_IN_ATTEMPTS
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public Byte getNumberOfSignInAttempts() {
        return numberOfSignInAttempts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account.NUMBER_OF_SIGN_IN_ATTEMPTS
     *
     * @param numberOfSignInAttempts the value for tbl_user_account.NUMBER_OF_SIGN_IN_ATTEMPTS
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setNumberOfSignInAttempts(Byte numberOfSignInAttempts) {
        this.numberOfSignInAttempts = numberOfSignInAttempts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account.CATEGORY_RELATION_ID
     *
     * @return the value of tbl_user_account.CATEGORY_RELATION_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getCategoryRelationId() {
        return categoryRelationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account.CATEGORY_RELATION_ID
     *
     * @param categoryRelationId the value for tbl_user_account.CATEGORY_RELATION_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setCategoryRelationId(String categoryRelationId) {
        this.categoryRelationId = categoryRelationId == null ? null : categoryRelationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account.RELATION_ID
     *
     * @return the value of tbl_user_account.RELATION_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account.RELATION_ID
     *
     * @param relationId the value for tbl_user_account.RELATION_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setRelationId(String relationId) {
        this.relationId = relationId == null ? null : relationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account.ACTIVATE_DATETIME
     *
     * @return the value of tbl_user_account.ACTIVATE_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public Date getActivateDatetime() {
        return activateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account.ACTIVATE_DATETIME
     *
     * @param activateDatetime the value for tbl_user_account.ACTIVATE_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setActivateDatetime(Date activateDatetime) {
        this.activateDatetime = activateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account.TERMINATE_DATETIME
     *
     * @return the value of tbl_user_account.TERMINATE_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public Date getTerminateDatetime() {
        return terminateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account.TERMINATE_DATETIME
     *
     * @param terminateDatetime the value for tbl_user_account.TERMINATE_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setTerminateDatetime(Date terminateDatetime) {
        this.terminateDatetime = terminateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account.COMMENT
     *
     * @return the value of tbl_user_account.COMMENT
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account.COMMENT
     *
     * @param comment the value for tbl_user_account.COMMENT
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account.STATUS
     *
     * @return the value of tbl_user_account.STATUS
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account.STATUS
     *
     * @param status the value for tbl_user_account.STATUS
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account.SORT_ORDER
     *
     * @return the value of tbl_user_account.SORT_ORDER
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account.SORT_ORDER
     *
     * @param sortOrder the value for tbl_user_account.SORT_ORDER
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account.INSERT_USER_ID
     *
     * @return the value of tbl_user_account.INSERT_USER_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getInsertUserId() {
        return insertUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account.INSERT_USER_ID
     *
     * @param insertUserId the value for tbl_user_account.INSERT_USER_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setInsertUserId(String insertUserId) {
        this.insertUserId = insertUserId == null ? null : insertUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account.INSERT_DATETIME
     *
     * @return the value of tbl_user_account.INSERT_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public Date getInsertDatetime() {
        return insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account.INSERT_DATETIME
     *
     * @param insertDatetime the value for tbl_user_account.INSERT_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setInsertDatetime(Date insertDatetime) {
        this.insertDatetime = insertDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account.UPDATE_USER_ID
     *
     * @return the value of tbl_user_account.UPDATE_USER_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account.UPDATE_USER_ID
     *
     * @param updateUserId the value for tbl_user_account.UPDATE_USER_ID
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_account.UPDATE_DATETIME
     *
     * @return the value of tbl_user_account.UPDATE_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_account.UPDATE_DATETIME
     *
     * @param updateDatetime the value for tbl_user_account.UPDATE_DATETIME
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }
}