package com.doerit.dao;

import com.doerit.model.ActionTemplate;
import com.doerit.model.ActionTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActionTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_action_template
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int countByExample(ActionTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_action_template
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int deleteByExample(ActionTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_action_template
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_action_template
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int insert(ActionTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_action_template
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int insertSelective(ActionTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_action_template
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    List<ActionTemplate> selectByExample(ActionTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_action_template
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    ActionTemplate selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_action_template
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int updateByExampleSelective(@Param("record") ActionTemplate record, @Param("example") ActionTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_action_template
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int updateByExample(@Param("record") ActionTemplate record, @Param("example") ActionTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_action_template
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int updateByPrimaryKeySelective(ActionTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_action_template
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int updateByPrimaryKey(ActionTemplate record);
}