package com.doerit.dao;

import com.doerit.model.Action;
import com.doerit.model.ActionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UrlActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_action
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int countByExample(ActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_action
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int deleteByExample(ActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_action
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_action
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int insert(Action record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_action
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int insertSelective(Action record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_action
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    List<Action> selectByExample(ActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_action
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    Action selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_action
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int updateByExampleSelective(@Param("record") Action record, @Param("example") ActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_action
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int updateByExample(@Param("record") Action record, @Param("example") ActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_action
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int updateByPrimaryKeySelective(Action record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_action
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int updateByPrimaryKey(Action record);
}