package com.doerit.dao;

import com.doerit.model.UserAccountAction;
import com.doerit.model.UserAccountActionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAccountActionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_account_action
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int countByExample(UserAccountActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_account_action
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int deleteByExample(UserAccountActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_account_action
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_account_action
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int insert(UserAccountAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_account_action
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int insertSelective(UserAccountAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_account_action
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    List<UserAccountAction> selectByExample(UserAccountActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_account_action
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    UserAccountAction selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_account_action
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int updateByExampleSelective(@Param("record") UserAccountAction record, @Param("example") UserAccountActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_account_action
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int updateByExample(@Param("record") UserAccountAction record, @Param("example") UserAccountActionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_account_action
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int updateByPrimaryKeySelective(UserAccountAction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_account_action
     *
     * @mbggenerated Sun Jul 09 08:24:40 IST 2017
     */
    int updateByPrimaryKey(UserAccountAction record);
}